console.log("************************")
console.log("*      ℜ𝔢𝔭𝔬𝔯𝔱 ℭ𝔞𝔯𝔡     *")
console.log("*......................*")
console.log("*     𝓢𝓸𝓾𝓻𝓪𝓿 𝓓𝓱𝓾𝓪     *")
console.log("*......................*")
//school, grade, section, roll no
console.log("* 𝙱𝚊𝚗𝚔𝚞𝚛𝚊 𝚉𝚒𝚕𝚕𝚊 𝚂𝚌𝚑𝚘𝚘𝚕 *")
console.log("*......................*")
console.log("*  Grade:- A           *")
console.log("*  Section B           *")
console.log("*  Roll No: 36         *")
console.log("*......................*")
console.log("*    𝑂𝑏𝑡𝑎𝑖𝑛𝑒𝑑 𝑀𝑎𝑟𝑘𝑠    *")
console.log("*......................*")
console.log("*  Physics :     90    *")
console.log("*  Chemistry:    70    *")
console.log("*  Mathematics : 85    *")
console.log("************************")